#!/bin/bash
# ----------------------------------------------------------------------
#	Copyright (c) 2014
#
#	This program is free software; you can redistribute it and/or
#	modify it under the terms of version 3 of the GNU General Public
#	License published by the Free Software Foundation.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
# ----------------------------------------------------------------------
# Authors:
#	Alex V Kotelnikov (aka gudron) <gudron@gudron.me>
#
# Repository:
#	https://github.com/gudron/jailcoopy
#
# /usr/local/bin/jailcoopy

BIN_NAME=""
JAIL_ROOT=""
LIST=""

execPath=`pwd`

usage() {
	sn=`basename $0`
	
	echo "USAGE: $sn -n <BINARY_NAME> -j <JAIL_ROOT>"
	echo "USAGE: $sn -l <LIST> -j <JAIL_ROOT>"
	echo -e "Options:"
	echo -e "\t-n <BINARY_NAME>\tBinary application name.\t Example: bash, sh, rsync"
	echo -e "\t-j <JAIL_ROOT>\t\tJailroot path.\t\t\t Example: /home/virtualhosts/example.dev	"
	echo -e "\t-l <LIST>\tList of binary file names.\t Example: 'sh,bash,ssh,rsync"
}

printError() {
	echo "[!] Invalid option" && usage && exit 1
}

function linkIntoJail {
	#linkPath - $1
	#binPath - $2
	local linkPath=$1
	local linkName=`basename "$linkPath"`
	local binPath=$2
	dirPath=`dirname $linkPath`
	if [ ! -d "$JAIL_ROOT$dirPath" ]; then
		mkdir -p "$JAIL_ROOT$dirPath"
	fi
	cd "$JAIL_ROOT$dirPath" && ln -s "$binPath" "$linkName" && cd "$execPath"
}

function copyToJail {
	dirPath=`dirname $1`
	if [ ! -d "$JAIL_ROOT$dirPath" ]; then
		mkdir -p $JAIL_ROOT$dirPath
	fi
	cp $1 $JAIL_ROOT$dirPath
}

function findSoLibrary () {
	while IFS= read -r line
	do
		libName=`echo "$line" | awk '{print $1}'`
		libPath=`echo "$line" | awk '{print $3}'`

		if [ -s $libPath ] && [ -f $libPath ] && [ -e $libPath ] && [ ! -z "$libPath" -a "$libPath" != " " ]
		then
			copyToJail $libPath
		else
			if [ -s $libName ] && [ -f $libName ] && [ -e $libName ]
			then
				copyToJail $libName
			fi
		fi
	done <<< "$filesToCopy"

}

function copyBinFile () {
	local fileName=$1
	local fileExtension=""
	#binPath=`whereis $fileName | awk '{print $2}'`
	local binPath=`whereis $fileName`
	local binName=""
	IFS=' ' read -a nameArray <<< "$binPath"
	unset nameArray[0] #unset whereis header; example bash: /bin/bash . "bash:" unseted
	for element in "${nameArray[@]}"
	do
		if [ -f "$element" ]
		then
			baseName=`basename "$element"`
			mimeType=`file -h --mime-type "$element" | awk '{print $2}'`
			binName=$element;
			case $mimeType in
				"inode/symlink" )
					binName=`readlink "$element"`
					linkedBinPath=`readlink -f "$element"`
					filesToCopy=`ldd $linkedBinPath`
					findSoLibrary filesToCopy
					copyToJail $linkedBinPath
					linkIntoJail $element $binName #;&
					;;
				"application/x-executable" ) 
					filesToCopy=`ldd $binName`
					findSoLibrary filesToCopy
					copyToJail $element
				;;
				* ) 
				copyToJail $element;;
			esac
		fi
	done
}

function main () {
	execPath=`pwd`
	if [ "$LIST" != "" ]
	then
		IFS=',' read -a binNameArray <<< "$LIST"
		for element in "${binNameArray[@]}"
		do
			copyBinFile "$element"
		done
	else
		copyBinFile "$BIN_NAME"
	fi
}

while getopts "n:j:l:" Option; do
	case $Option in
			n ) BIN_NAME="$OPTARG";;
			j ) JAIL_ROOT="$OPTARG";;
			l ) LIST="$OPTARG";;
			* ) printError;;
	esac
done

if [ "$JAIL_ROOT" != "" ] && { [ "$LIST" != "" ] || [ "$BIN_NAME" != "" ]; } then
	main
else
	printError
fi

exit 0