#!/bin/bash
# ----------------------------------------------------------------------
#    Copyright (c) 2014
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of version 3 of the GNU General Public
#    License published by the Free Software Foundation.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
# ----------------------------------------------------------------------
# Authors:
#  Alex V Kotelnikov (aka gudron) <gudron@gudron.me>
#
# /usr/local/bin/jailcoopy
BIN_NAME=""
JAIL_ROOT=""

usage() {
	echo "USAGE: $0 -n <BINARY_NAME> -j <JAIL_ROOT>"
	echo -e "Options:"
	echo -e "\t-n <BINARY_NAME>\tBinary application name.\t Example: bash, sh, rsync"
	echo -e "\t-j <JAIL_ROOT>\t\tJailroot path.\t\t\t Example: /home/virtualhosts/example.dev	"
}

printError() {
	echo "[!] Invalid option" && usage && exit 1
}

function copyToJail {
	dirPath=`dirname $1`
	echo "copy $1 to $JAIL_ROOT$dirPath"		
	mkdir -p $JAIL_ROOT$dirPath
	cp $1 $JAIL_ROOT$dirPath
}

function findSoLibrary () {
	while IFS= read -r line
	do
		libName=`echo "$line" | awk '{print $1}'`
		libPath=`echo "$line" | awk '{print $3}'`

		if [ -s $libPath ] && [ -f $libPath ] && [ -e $libPath ] && [ ! -z "$libPath" -a "$libPath" != " " ]
		then
			copyToJail $libPath
		else
			if [ -s $libName ] && [ -f $libName ] && [ -e $libName ]
			then
				copyToJail $libName
			fi
		fi
	done <<< "$filesToCopy"

}

function main() {
	binPath=`whereis $BIN_NAME | awk '{print $2}'`
	filesToCopy=`ldd $binPath`

	findSoLibrary filesToCopy
	copyToJail $binPath
}

while getopts "n:j:" Option; do
	case $Option in
		n ) BIN_NAME="$OPTARG";;
		j ) JAIL_ROOT="$OPTARG";;
		* ) printError;;
	esac
done

if [ "$BIN_NAME" != "" -a "$JAIL_ROOT" != "" ]
then
	main
else
	printError
fi

exit 0